version: '3.8'

services:
  bandit:
    build:
      context: .
      dockerfile: Dockerfile.bandit
    volumes:
      - ./reports:/app/reports

  shellcheck:
    build:
      context: .
      dockerfile: Dockerfile.shellcheck
    volumes:
      - ./reports:/app/reports

  combine-reports:
    image: python:3.9-slim
    volumes:
      - ./reports:/app/reports
      - .:/app
    working_dir: /app
    command: ["python", "combine_reports.py"]

